const express = require("express");
const cors = require("cors");
const bodyParser = require("body-parser");
const chance = require("chance").Chance();

const app = express();
const port = 3000;
app.use(cors());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

//Info Ferran
const fb = {
  S: [true],
  O: [
    {
      T: "pHnAg5M_UV2eNft6JYjLM6wGvWM=",
      P: {
        anyAcademic: "null",
        numSolicitud: "11691",
        dataSolicitud: "1670112000000",
        codiCertificat: "PROGDIG",
        estatSolicitud: "A",
        descCertificat: "Plan de estudios y programas docentes",
        descEstatSolicitud: "Aceptada",
      },
      R: "2",
      Y: 71,
    },
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "A",
        secSolicitud: "389523",
        fechaSolicitud: "1656922138000",
        descEstado: "Aceptada",
      },
      R: "2",
      Y: 70,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "A",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Uso de bases de datos",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.567",
      },
      R: "2",
      Y: 26,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Proyecto de desarrollo del software",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.588",
        qualificacioQuantitativaFinal: 8.4,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 12,
        tipus: "1",
        ultAnyMatricula: "2022/23-1",
      },
      R: "2",
      Y: 61,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20192",
        estat: "A",
        descAnyAcademic: "2019/20-2",
        descAssignatura: "Fundamentos físicos de la informática",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.611",
      },
      R: "2",
      Y: 25,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Sistemas distribuidos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.589",
        qualificacioQuantitativaFinal: 7.8,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 62,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "A",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Estructura de computadores",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.573",
      },
      R: "2",
      Y: 28,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Interacción persona ordenador",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.590",
        qualificacioQuantitativaFinal: 8.2,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 63,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "D",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Grafos y complejidad",
        descEstat: "Denegada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.569",
      },
      R: "2",
      Y: 27,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Ingeniería de requisitos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.593",
        qualificacioQuantitativaFinal: 7.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 64,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos físicos de la informática",
        descripcioClasseCredits: "Básica",
        codi: "75.611",
        qualificacioQuantitativaFinal: 8.4,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 65,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20202",
        estat: "A",
        descAnyAcademic: "2020/21-2",
        descAssignatura: "Sistemas operativos",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.566",
      },
      R: "2",
      Y: 29,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Diseño de estructuras de datos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.613",
        qualificacioQuantitativaFinal: 6.5,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 66,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Practicas en empresa",
        descripcioClasseCredits: "Optativa",
        codi: "75.615",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 12,
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 67,
    },
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "D",
        secSolicitud: "294606",
        codMotivoDene: "IMPAG",
        fechaSolicitud: "1488818446000",
        descEstado: "Denegada - Denegada per error en el proceso de pago",
      },
      R: "2",
      Y: 68,
    },
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "A",
        secSolicitud: "294701",
        fechaSolicitud: "1488887504000",
        descEstado: "Aceptada",
      },
      R: "2",
      Y: 69,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20192",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2019/20-2",
        dataSolicitud: "1578351600000",
        numSolicitud: "1058363",
        estatSolicitud: "D",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Denegada",
      },
      R: "2",
      Y: 20,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20182",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2018/19-2",
        dataSolicitud: "1553814000000",
        numSolicitud: "1006683",
        estatSolicitud: "D",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Denegada",
      },
      R: "2",
      Y: 22,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20182",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2018/19-2",
        dataSolicitud: "1562191200000",
        numSolicitud: "1008241",
        estatSolicitud: "D",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Denegada",
      },
      R: "2",
      Y: 21,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20192",
        estat: "A",
        descAnyAcademic: "2019/20-2",
        descAssignatura: "Interacción persona ordenador",
        descEstat: "Aceptada",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "75.590",
      },
      R: "2",
      Y: 24,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20181",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2018/19-1",
        dataSolicitud: "1532642400000",
        numSolicitud: "942579",
        estatSolicitud: "D",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Denegada",
      },
      R: "2",
      Y: 23,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Ing. del software de componentes y sistemas distribuidos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.587",
        qualificacioQuantitativaFinal: 7.5,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 60,
    },
    {
      T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=",
      P: {
        primerCognom: "Ciriero",
        segonCognom: "Sánchez",
        idp: 940671,
        userLogin: "ecirieros",
        dni: "06996671W",
        nom: "Emilio Carlos",
      },
      R: "2",
      Y: 17,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Lógica",
        descripcioClasseCredits: "Básica",
        codi: "75.570",
        qualificacioQuantitativaFinal: 7.1,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 52,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada a petición del estudiante",
        codMotivoDene: "SOLESTUD",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 16,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Gestión de proyectos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.571",
        qualificacioQuantitativaFinal: 7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2018/19-2",
      },
      R: "2",
      Y: 53,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Solicitud docencia",
        codMotivoDene: "SOLDC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 15,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Estadística",
        descripcioClasseCredits: "Básica",
        codi: "75.568",
        qualificacioQuantitativaFinal: 6.3,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2018/19-2",
      },
      R: "2",
      Y: 50,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Revisada (no corresponde ninguna convalidación)",
        codMotivoDene: "REVIS",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 14,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Grafos y complejidad",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.569",
        qualificacioQuantitativaFinal: 6.9,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 51,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Administración de redes y sistemas operativos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.575",
        qualificacioQuantitativaFinal: 9.1,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "EX",
        descripcioQualificacioQualitativaFinal: "Sobresaliente",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 56,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Inteligencia artificial",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.582",
        qualificacioQuantitativaFinal: 8.2,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 57,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20192",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2019/20-2",
        dataSolicitud: "1580425200000",
        numSolicitud: "1060850",
        estatSolicitud: "D",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Denegada",
      },
      R: "2",
      Y: 19,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Redes y aplicaciones Internet",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.572",
        qualificacioQuantitativaFinal: 10,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "EX",
        descripcioQualificacioQualitativaFinal: "Sobresaliente",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 54,
    },
    {
      T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=",
      P: {
        anyAcademic: "20192",
        codiCamiDesti: "INGSOFT",
        descAnyAcademic: "2019/20-2",
        dataSolicitud: "1594072800000",
        numSolicitud: "1100235",
        estatSolicitud: "A",
        descripcioCamiDesti: "Itinerario en Ingeniería del software",
        descEstatSolicitud: "Aceptada",
      },
      R: "2",
      Y: 18,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 2,
        descripcio: "Estructura de computadores",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.573",
        qualificacioQuantitativaFinal: 8.3,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 55,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Diseño de bases de datos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.585",
        qualificacioQuantitativaFinal: 8.4,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 58,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Análisis y diseño con patrones",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.586",
        qualificacioQuantitativaFinal: 7.1,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 59,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada por normativa",
        codMotivoDene: "NOR",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 13,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada porque no procede",
        codMotivoDene: "NOPROC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 12,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion:
          "Denegada por falta documentación de los estudios de acceso",
        codMotivoDene: "NODOCACC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 11,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada per falta de documentación",
        codMotivoDene: "MANDOC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 10,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Sistemas operativos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.566",
        qualificacioQuantitativaFinal: 8.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 48,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Ingeniería del software",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.565",
        qualificacioQuantitativaFinal: 6.2,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-2",
      },
      R: "2",
      Y: 47,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Uso de bases de datos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.567",
        qualificacioQuantitativaFinal: 8.5,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 49,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos de computadores",
        descripcioClasseCredits: "Básica",
        codi: "75.562",
        qualificacioQuantitativaFinal: 5.5,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-2",
      },
      R: "2",
      Y: 44,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Trabajo en equipo en la Red",
        descripcioClasseCredits: "Básica",
        codi: "75.561",
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 43,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Diseño y programación orientada a objetos",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.564",
        qualificacioQuantitativaFinal: 8.6,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 46,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Competencia comunicativa para profesionales de las TIC",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.563",
        qualificacioQuantitativaFinal: 5.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-2",
      },
      R: "2",
      Y: 45,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Análisis matemático",
        descripcioClasseCredits: "Básica",
        codi: "75.558",
        qualificacioQuantitativaFinal: 8,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-1",
      },
      R: "2",
      Y: 40,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Idioma moderno II: Inglés",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.560",
        qualificacioQuantitativaFinal: 8,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 42,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Idioma moderno I: Inglés",
        descripcioClasseCredits: "Obligatoria",
        codi: "75.559",
        qualificacioQuantitativaFinal: 7.9,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-1",
      },
      R: "2",
      Y: 41,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 68 },
        numReconocimientos: 0,
      },
      R: "2",
      Y: 4,
    },
    {
      T: "1WNiS_NQH7GCRNTiIl2g1nIcgMM=",
      P: {
        numCreditsObligatoriSuperat: 132,
        numCreditsOptatiuSuperat: 36,
        numCreditsObligatoriObjectiu: 144,
        numCreditsTroncalSuperat: 60,
        numCreditsOptatiuObjectiu: 36,
        numCreditsTroncalObjectiu: 60,
        numExpedient: 1369293,
      },
      R: "2",
      Y: 3,
    },
    {
      T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=",
      P: {
        tipusEducacio: "EEES",
        primerSegonCicle: false,
        cicle: 1,
        codPla: "GR55",
      },
      R: "2",
      Y: 2,
    },
    {
      T: "RHcWxB19zK9mb9$lOHQm8SO7ofs=",
      P: {
        idpConectado: "889545",
        pla: { T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=", R: "2", Y: 2 },
        certificats: [{ T: "XGhl$81QmbUgS9EZJqobgd248iU=", R: "2", Y: 33 }],
        tipusEducacio: "EEES",
        progreso: { T: "1WNiS_NQH7GCRNTiIl2g1nIcgMM=", R: "2", Y: 3 },
        descOpcioAcces: "Ciclo Formativo de Grado Superior",
        descPlan: "Grado de Ingeniería Informática",
        solicitudesAEP: [
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 4 },
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 5 },
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 6 },
        ],
        expedientVO: { T: "sSIxO6pqzrwLhLd3PZFzpndhF1A=", R: "2", Y: 34 },
        allMotivosDenegacion: [
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 7 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 8 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 9 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 10 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 11 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 12 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 13 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 14 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 15 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 16 },
        ],
        listaAsignaturas: [
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 35 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 36 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 37 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 38 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 39 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 40 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 41 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 42 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 43 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 44 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 45 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 46 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 47 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 48 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 49 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 50 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 51 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 52 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 53 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 54 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 55 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 56 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 57 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 58 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 59 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 60 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 61 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 62 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 63 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 64 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 65 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 66 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 67 },
        ],
        numExpedient: 1369293,
        numSolAcc: 1858799,
        mostrarNotaMedia: "N",
        idApl: "GAT_EXP",
        tutor: { T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=", R: "2", Y: 17 },
        itineraris: [
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 18 },
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 19 },
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 20 },
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 21 },
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 22 },
          { T: "ua6oBq2$2vD_EV3hJJ2wzqrkrPQ=", R: "2", Y: 23 },
        ],
        provesVirtuals: [
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 24 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 25 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 26 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 27 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 28 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 29 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 30 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 31 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 32 },
        ],
      },
      R: "2",
      Y: 1,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegación y retorno del importe",
        codMotivoDene: "DENTAXA",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 7,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada per error en el proceso de pago",
        codMotivoDene: "IMPAG",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 8,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 69 },
        numReconocimientos: 2,
      },
      R: "2",
      Y: 5,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 70 },
        numReconocimientos: 1,
      },
      R: "2",
      Y: 6,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Álgebra",
        descripcioClasseCredits: "Básica",
        codi: "75.557",
        qualificacioQuantitativaFinal: 6.1,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-1",
      },
      R: "2",
      Y: 39,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Administración y gestión de organizaciones",
        descripcioClasseCredits: "Básica",
        codi: "75.556",
        qualificacioQuantitativaFinal: 6.9,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-2",
      },
      R: "2",
      Y: 38,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Prácticas de programación",
        descripcioClasseCredits: "Básica",
        codi: "75.555",
        qualificacioQuantitativaFinal: 8,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-1",
      },
      R: "2",
      Y: 37,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion:
          "Denegada per falta del certificado de notas o certificado incorrecto",
        codMotivoDene: "MANCAP",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 9,
    },
    {
      T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=",
      P: {
        primerCognom: "Bals",
        segonCognom: "Moreno",
        idp: 889545,
        userLogin: "fbals",
        dni: "47745843M",
        nom: "Ferran",
      },
      R: "2",
      Y: 72,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos de programación",
        descripcioClasseCredits: "Básica",
        codi: "75.554",
        qualificacioQuantitativaFinal: 7.6,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-1",
      },
      R: "2",
      Y: 36,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Mínor de Programación Web",
        descripcioClasseCredits: "Optativa",
        codi: "MINMUL4",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 24,
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 35,
    },
    {
      T: "sSIxO6pqzrwLhLd3PZFzpndhF1A=",
      P: {
        pla: { T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=", R: "2", Y: 2 },
        indEstatExpedient: "A",
        tercer: { T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=", R: "2", Y: 72 },
        numSolAcc: 1858799,
        idpTutor: 940671,
        idIniciativa: 1,
        descEstatExpedient: "Abierto",
        codCentre: 700,
        notaMitjana: 7.65,
        divisio: "GAT",
        numExpedient: 1369293,
      },
      R: "2",
      Y: 34,
    },
    {
      T: "XGhl$81QmbUgS9EZJqobgd248iU=",
      P: {
        idDocumentPortaSignatura: "429757",
        solCertificatVO: { T: "pHnAg5M_UV2eNft6JYjLM6wGvWM=", R: "2", Y: 71 },
        esGdd: true,
      },
      R: "2",
      Y: 33,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20211",
        estat: "V",
        descAnyAcademic: "2021/22-1",
        descAssignatura: "Inteligencia artificial",
        descEstat: "Registro facial válido",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "75.582",
      },
      R: "2",
      Y: 32,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20202",
        estat: "A",
        descAnyAcademic: "2020/21-2",
        descAssignatura: "Análisis y diseño con patrones",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.586",
      },
      R: "2",
      Y: 31,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20202",
        estat: "A",
        descAnyAcademic: "2020/21-2",
        descAssignatura: "Diseño de bases de datos",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "75.585",
      },
      R: "2",
      Y: 30,
    },
  ],
  I: [{ T: "RHcWxB19zK9mb9$lOHQm8SO7ofs=", R: "2", Y: 1 }],
};
//Info Carlos
const cr = {
  S: [true],
  O: [
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "D",
        secSolicitud: "342314",
        codMotivoDene: "IMPAG",
        fechaSolicitud: "1583150666000",
        descEstado: "Denegada - Denegada per error en el proceso de pago",
      },
      R: "2",
      Y: 71,
    },
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "A",
        secSolicitud: "315537",
        fechaSolicitud: "1531476814000",
        descEstado: "Aceptada",
      },
      R: "2",
      Y: 70,
    },
    {
      T: "sSIxO6pqzrwLhLd3PZFzpndhF1A=",
      P: {
        pla: { T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=", R: "2", Y: 2 },
        indEstatExpedient: "A",
        tercer: { T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=", R: "2", Y: 74 },
        numSolAcc: 1838700,
        idpTutor: 379771,
        idIniciativa: 1,
        descEstatExpedient: "Abierto",
        codCentre: 700,
        notaMitjana: 6.8,
        divisio: "GAT",
        numExpedient: 1357302,
      },
      R: "2",
      Y: 26,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Investigación de mercados ",
        descripcioClasseCredits: "Optativa",
        codi: "71.550",
        codiClasseCredits: "P",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2022/23-1",
      },
      R: "2",
      Y: 61,
    },
    {
      T: "XGhl$81QmbUgS9EZJqobgd248iU=",
      P: {
        idDocumentPortaSignatura: "61530",
        solCertificatVO: { T: "pHnAg5M_UV2eNft6JYjLM6wGvWM=", R: "2", Y: 73 },
        esGdd: false,
      },
      R: "2",
      Y: 25,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Uso de los sistemas de información en las organizaciones",
        descripcioClasseCredits: "Optativa",
        codi: "71.556",
        qualificacioQuantitativaFinal: 8.6,
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 62,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Introducción a la empresa  ",
        descripcioClasseCredits: "Básica",
        codi: "71.500",
        qualificacioQuantitativaFinal: 8,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2015/16-2",
      },
      R: "2",
      Y: 28,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Trabajo final de grado",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.562",
        codiClasseCredits: "O",
        descripcioTFCAssociat: "TFG - Plan de empresa",
        codiTFCAssociat: "71.583",
        numCredits: 6,
        tipus: "3",
        ultAnyMatricula: "2022/23-1",
      },
      R: "2",
      Y: 63,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Reconocimiento créditos RECAAU",
        descripcioClasseCredits: "Optativa",
        codi: "RECAAU",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 2,
        ultAnyMatricula: "2018/19-2",
      },
      R: "2",
      Y: 27,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Prácticas empresariales II",
        descripcioClasseCredits: "Optativa",
        codi: "71.576",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 64,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Business Game: Simulación de negocios",
        descripcioClasseCredits: "Optativa",
        codi: "71.579",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 65,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos de estadística",
        descripcioClasseCredits: "Básica",
        codi: "71.501",
        qualificacioQuantitativaFinal: 7.3,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 29,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Prácticas empresariales I",
        descripcioClasseCredits: "Optativa",
        codi: "71.582",
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 66,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Gestión de proyectos",
        descripcioClasseCredits: "Optativa",
        codi: "76.527",
        qualificacioQuantitativaFinal: 4.1,
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "SU",
        descripcioQualificacioQualitativaFinal: "Suspendido",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-2",
      },
      R: "2",
      Y: 67,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Introducción al Business Intelligence",
        descripcioClasseCredits: "Optativa",
        codi: "78.619",
        qualificacioQuantitativaFinal: 6.5,
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 68,
    },
    {
      T: "UQ$35a35sXmaVPEidrhb78g8N4E=",
      P: {
        reconeixements: [
          { T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=", R: "2", Y: 79 },
          { T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=", R: "2", Y: 80 },
          { T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=", R: "2", Y: 81 },
        ],
        solicitudRAEP: { T: "fpv49ePek7twt6DbXQbPb6YJ93Q=", R: "2", Y: 75 },
        aportats: [
          { T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=", R: "2", Y: 76 },
          { T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=", R: "2", Y: 77 },
          { T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=", R: "2", Y: 78 },
        ],
      },
      R: "2",
      Y: 69,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "A",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Derecho de la empresa",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "71.512",
      },
      R: "2",
      Y: 20,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "A",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Inversión empresarial",
        descEstat: "Aceptada",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "71.527",
      },
      R: "2",
      Y: 22,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20201",
        estat: "A",
        descAnyAcademic: "2020/21-1",
        descAssignatura: "Valoración de operaciones financieras",
        descEstat: "Aceptada",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "71.523",
      },
      R: "2",
      Y: 21,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20211",
        estat: "V",
        descAnyAcademic: "2021/22-1",
        descAssignatura: "Fiscalidad empresarial",
        descEstat: "Registro facial válido",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "71.514",
      },
      R: "2",
      Y: 24,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20202",
        estat: "A",
        descAnyAcademic: "2020/21-2",
        descAssignatura: "Fiscalidad empresarial",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "71.514",
      },
      R: "2",
      Y: 23,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Gestión del cambio",
        descripcioClasseCredits: "Optativa",
        codi: "71.546",
        qualificacioQuantitativaFinal: 7,
        codiClasseCredits: "P",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 60,
    },
    {
      T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=",
      P: {
        primerCognom: "Vidal",
        segonCognom: "Martinez",
        idp: 379771,
        userLogin: "gvidalma",
        dni: "43712839M",
        nom: "Gabriel",
      },
      R: "2",
      Y: 17,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Análisis de los estados financieros",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.524",
        qualificacioQuantitativaFinal: 6.2,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-1",
      },
      R: "2",
      Y: 52,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada a petición del estudiante",
        codMotivoDene: "SOLESTUD",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 16,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Financiación empresarial",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.525",
        qualificacioQuantitativaFinal: 8.4,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 53,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Solicitud docencia",
        codMotivoDene: "SOLDC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 15,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Contabilidad financiera",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.522",
        qualificacioQuantitativaFinal: 6.9,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 50,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Revisada (no corresponde ninguna convalidación)",
        codMotivoDene: "REVIS",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 14,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Valoración de operaciones financieras",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.523",
        qualificacioQuantitativaFinal: 7.8,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 51,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Control presupuestario y de gestión",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.528",
        qualificacioQuantitativaFinal: 7.6,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-2",
      },
      R: "2",
      Y: 56,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Dirección de marketing",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.529",
        qualificacioQuantitativaFinal: 6.4,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-2",
      },
      R: "2",
      Y: 57,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20192",
        estat: "A",
        descAnyAcademic: "2019/20-2",
        descAssignatura: "Introducción a la contabilidad",
        descEstat: "Aceptada",
        tipusProva: "Prueba de síntesi virtual",
        codAssignatura: "71.520",
      },
      R: "2",
      Y: 19,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Contabilidad de costes",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.526",
        qualificacioQuantitativaFinal: 7.1,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-2",
      },
      R: "2",
      Y: 54,
    },
    {
      T: "atiod4vkRiNDS651NTVpY77vWZo=",
      P: {
        anyAcademic: "20192",
        estat: "A",
        descAnyAcademic: "2019/20-2",
        descAssignatura: "Introducción al derecho",
        descEstat: "Aceptada",
        tipusProva: "Examen virtual",
        codAssignatura: "71.503",
      },
      R: "2",
      Y: 18,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Inversión empresarial",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.527",
        qualificacioQuantitativaFinal: 7.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 55,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Idioma moderno II: Inglés",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.530",
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 58,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 0,
        descripcio: "Gestión de la innovación",
        descripcioClasseCredits: "Optativa",
        codi: "71.544",
        codiClasseCredits: "P",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2022/23-1",
      },
      R: "2",
      Y: 59,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada por normativa",
        codMotivoDene: "NOR",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 13,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada porque no procede",
        codMotivoDene: "NOPROC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 12,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion:
          "Denegada por falta documentación de los estudios de acceso",
        codMotivoDene: "NODOCACC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 11,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada per falta de documentación",
        codMotivoDene: "MANDOC",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 10,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Introducción a la contabilidad",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.520",
        qualificacioQuantitativaFinal: 7.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 48,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Personas y organizaciones",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.519",
        qualificacioQuantitativaFinal: 6.5,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2018/19-2",
      },
      R: "2",
      Y: 47,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Habilidades directivas",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.521",
        qualificacioQuantitativaFinal: 8,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 49,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos de matemáticas",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.516",
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 44,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Decisiones tácticas de producción",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.515",
        qualificacioQuantitativaFinal: 7.8,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 43,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Estadística aplicada",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.518",
        qualificacioQuantitativaFinal: 6.4,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 46,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Logística",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.517",
        qualificacioQuantitativaFinal: 6,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-1",
      },
      R: "2",
      Y: 45,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Derecho de la empresa",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.512",
        qualificacioQuantitativaFinal: 6.2,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 40,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 2,
        descripcio: "Fiscalidad empresarial",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.514",
        qualificacioQuantitativaFinal: 5.7,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2021/22-1",
      },
      R: "2",
      Y: 42,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 3,
        descripcio: "Dirección estratégica",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.513",
        codiClasseCredits: "O",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2022/23-1",
      },
      R: "2",
      Y: 41,
    },
    {
      T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=",
      P: {
        rolReconocido: "Expriencia básica",
        anyAcademico: "20212",
        numCreditos: 6,
        claseAsignatura: "Optativa",
        asignatura: "Prácticas empresariales I",
        numMatricula: "10",
      },
      R: "2",
      Y: 81,
    },
    {
      T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=",
      P: {
        rolReconocido: "Experiencia avanzada",
        anyAcademico: "20212",
        numCreditos: 6,
        claseAsignatura: "Optativa",
        asignatura: "Business Game: Simulación de negocios",
        numMatricula: "10",
      },
      R: "2",
      Y: 80,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 70 },
        numReconocimientos: 1,
      },
      R: "2",
      Y: 4,
    },
    {
      T: "1WNiS_NQH7GCRNTiIl2g1nIcgMM=",
      P: {
        numCreditsObligatoriSuperat: 120,
        numCreditsOptatiuSuperat: 38,
        numCreditsObligatoriObjectiu: 132,
        numCreditsTroncalSuperat: 60,
        numCreditsOptatiuObjectiu: 48,
        numCreditsTroncalObjectiu: 60,
        numExpedient: 1357302,
      },
      R: "2",
      Y: 3,
    },
    {
      T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=",
      P: {
        tipusEducacio: "EEES",
        primerSegonCicle: false,
        cicle: 1,
        codPla: "GR51",
      },
      R: "2",
      Y: 2,
    },
    {
      T: "RHcWxB19zK9mb9$lOHQm8SO7ofs=",
      P: {
        idpConectado: "880487",
        pla: { T: "eO2Chrn3K53ySuNj82jHgm9Qo_E=", R: "2", Y: 2 },
        certificats: [{ T: "XGhl$81QmbUgS9EZJqobgd248iU=", R: "2", Y: 25 }],
        tipusEducacio: "EEES",
        progreso: { T: "1WNiS_NQH7GCRNTiIl2g1nIcgMM=", R: "2", Y: 3 },
        descOpcioAcces: "PAU y estudios universitarios iniciados",
        descPlan: "Grado de Administración y Dirección de Empresas",
        solicitudesAEP: [
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 4 },
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 5 },
          { T: "NN$jjZrm84w_8AovFmxnnHU6giw=", R: "2", Y: 6 },
        ],
        expedientVO: { T: "sSIxO6pqzrwLhLd3PZFzpndhF1A=", R: "2", Y: 26 },
        allMotivosDenegacion: [
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 7 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 8 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 9 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 10 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 11 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 12 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 13 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 14 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 15 },
          { T: "fEsBQZocOtnSXQniJn0BbX9ILA0=", R: "2", Y: 16 },
        ],
        listaAsignaturas: [
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 27 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 28 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 29 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 30 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 31 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 32 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 33 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 34 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 35 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 36 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 37 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 38 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 39 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 40 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 41 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 42 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 43 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 44 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 45 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 46 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 47 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 48 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 49 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 50 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 51 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 52 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 53 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 54 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 55 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 56 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 57 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 58 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 59 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 60 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 61 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 62 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 63 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 64 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 65 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 66 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 67 },
          { T: "997hN7iymHHoU8BGqmuM0QMNPxs=", R: "2", Y: 68 },
        ],
        numExpedient: 1357302,
        numSolAcc: 1838700,
        mostrarNotaMedia: "N",
        idApl: "GAT_EXP",
        tutor: { T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=", R: "2", Y: 17 },
        provesVirtuals: [
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 18 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 19 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 20 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 21 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 22 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 23 },
          { T: "atiod4vkRiNDS651NTVpY77vWZo=", R: "2", Y: 24 },
        ],
        raeps: [{ T: "UQ$35a35sXmaVPEidrhb78g8N4E=", R: "2", Y: 69 }],
      },
      R: "2",
      Y: 1,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegación y retorno del importe",
        codMotivoDene: "DENTAXA",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 7,
    },
    {
      T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=",
      P: {
        codiEstatTramit: "A",
        codisMotiuDenegacioAlegables: "10,11,12",
        idpTutor: "379771",
        numTramit: "36357",
        codiOrigenAep: "775",
        descripcioElement: "Expriencia básica",
      },
      R: "2",
      Y: 78,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion: "Denegada per error en el proceso de pago",
        codMotivoDene: "IMPAG",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 8,
    },
    {
      T: "mP848T94Ol0wCkrLC_ZGFdpbf4I=",
      P: {
        rolReconocido: "Experiencia avanzada",
        anyAcademico: "20212",
        numCreditos: 6,
        claseAsignatura: "Optativa",
        asignatura: "Prácticas empresariales II",
        numMatricula: "10",
      },
      R: "2",
      Y: 79,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 71 },
        numReconocimientos: 0,
      },
      R: "2",
      Y: 5,
    },
    {
      T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=",
      P: {
        codiEstatTramit: "A",
        codisMotiuDenegacioAlegables: "10,11,12",
        idpTutor: "379771",
        numTramit: "36355",
        codiOrigenAep: "774",
        descripcioElement: "Experiencia avanzada",
      },
      R: "2",
      Y: 76,
    },
    {
      T: "NN$jjZrm84w_8AovFmxnnHU6giw=",
      P: {
        solicitudAEP: { T: "zgufyJB2ytYUEauhIrcVTwsXfLE=", R: "2", Y: 72 },
        numReconocimientos: 3,
      },
      R: "2",
      Y: 6,
    },
    {
      T: "OZpHU5qe5rM9XkYPQhsoX64OjtU=",
      P: {
        codiEstatTramit: "A",
        codisMotiuDenegacioAlegables: "10,11,12",
        idpTutor: "379771",
        numTramit: "36356",
        codiOrigenAep: "776",
        descripcioElement: "Experiencia intermedia",
      },
      R: "2",
      Y: 77,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Organización de empresas",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.511",
        qualificacioQuantitativaFinal: 5.3,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 39,
    },
    {
      T: "p_ovO$a_rkE0DzW9ZSC8AMXg5VQ=",
      P: {
        primerCognom: "Román",
        segonCognom: "Romero",
        idp: 880487,
        userLogin: "carlesr",
        dni: "77120262C",
        nom: "Carlos",
      },
      R: "2",
      Y: 74,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Estructura económica",
        descripcioClasseCredits: "Obligatoria",
        codi: "71.510",
        qualificacioQuantitativaFinal: 7.3,
        codiClasseCredits: "O",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2020/21-1",
      },
      R: "2",
      Y: 38,
    },
    {
      T: "fpv49ePek7twt6DbXQbPb6YJ93Q=",
      P: {
        anyAcademic: "20212",
        dataResolucio: "1641164400000",
        descAnyAcademic: "2021/22-2",
        numSolicitud: "24672",
        dataSolicitud: "1637190000000",
        estatSolicitud: "A",
        descEstatSolicitud: "Aceptada",
      },
      R: "2",
      Y: 75,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Idioma moderno I: Inglés",
        descripcioClasseCredits: "Básica",
        codi: "71.509",
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "C",
        descripcioQualificacioQualitativaFinal: "Reconocido",
        numCredits: 6,
        ultAnyMatricula: "2020/21-2",
      },
      R: "2",
      Y: 37,
    },
    {
      T: "fEsBQZocOtnSXQniJn0BbX9ILA0=",
      P: {
        descripcion:
          "Denegada per falta del certificado de notas o certificado incorrecto",
        codMotivoDene: "MANCAP",
        tipoMotivoDene: "DENEGSOL",
      },
      R: "2",
      Y: 9,
    },
    {
      T: "zgufyJB2ytYUEauhIrcVTwsXfLE=",
      P: {
        entidadGestora: "0",
        estado: "A",
        secSolicitud: "342315",
        fechaSolicitud: "1583151284000",
        descEstado: "Aceptada",
      },
      R: "2",
      Y: 72,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Comportamiento de los agregados económicos ",
        descripcioClasseCredits: "Básica",
        codi: "71.508",
        qualificacioQuantitativaFinal: 7,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2015/16-2",
      },
      R: "2",
      Y: 36,
    },
    {
      T: "pHnAg5M_UV2eNft6JYjLM6wGvWM=",
      P: {
        anyAcademic: "20152",
        descIdiomaCertificat: "Español",
        descAnyAcademic: "2015/16-2",
        numSolicitud: "802331",
        dataSolicitud: "1467324000000",
        codiCertificat: "ACTIC",
        estatSolicitud: "A",
        descCertificat: "Acreditación de competencias en TIC",
        descEstatSolicitud: "Aceptada",
        codiIdiomaCertificat: "CAS",
      },
      R: "2",
      Y: 73,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Iniciación a las competencias TIC",
        descripcioClasseCredits: "Básica",
        codi: "71.507",
        qualificacioQuantitativaFinal: 6,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numDecimalsQuantitativaFinal: 1,
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2015/16-2",
      },
      R: "2",
      Y: 35,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Mercados y conducta",
        descripcioClasseCredits: "Básica",
        codi: "71.506",
        qualificacioQuantitativaFinal: 5.7,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 34,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 2,
        descripcio: "Iniciativa emprendedora ",
        descripcioClasseCredits: "Básica",
        codi: "71.505",
        qualificacioQuantitativaFinal: 5.5,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2017/18-1",
      },
      R: "2",
      Y: 33,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Fundamentos de marketing",
        descripcioClasseCredits: "Básica",
        codi: "71.504",
        qualificacioQuantitativaFinal: 5,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-1",
      },
      R: "2",
      Y: 32,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Introducción al derecho",
        descripcioClasseCredits: "Básica",
        codi: "71.503",
        qualificacioQuantitativaFinal: 7.5,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "NO",
        descripcioQualificacioQualitativaFinal: "Notable",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2019/20-2",
      },
      R: "2",
      Y: 31,
    },
    {
      T: "997hN7iymHHoU8BGqmuM0QMNPxs=",
      P: {
        numConvocatoriesConsumides: 1,
        descripcio: "Introducción a la información financiera de la empresa",
        descripcioClasseCredits: "Básica",
        codi: "71.502",
        qualificacioQuantitativaFinal: 5,
        codiClasseCredits: "B",
        codiQualificacioQualitativaFinal: "A",
        descripcioQualificacioQualitativaFinal: "Aprobado",
        numCredits: 6,
        tipus: "1",
        ultAnyMatricula: "2016/17-1",
      },
      R: "2",
      Y: 30,
    },
  ],
  I: [{ T: "RHcWxB19zK9mb9$lOHQm8SO7ofs=", R: "2", Y: 1 }],
};

const loginUser = {
  tokenId: chance.guid(),
  name: chance.name(),
  lastName: chance.last(),
  email: chance.email({ domain: "addressapi.com" }),
  password: chance.string({ length: 10 }),
};

let response = {
  error: false,
  code: 200,
  message: "",
};

app.get("/", function (req, res) {
  response = {
    error: true,
    code: 200,
    message: "API REST working.",
  };
  res.send(response);
});

app.route("/expediente/fb").get(function (req, res) {
  response = {
    error: false,
    code: 200,
    message: "Expediente Ferran",
    data: fb,
  };

  res.send(response);
});

app.route("/expediente/cr").get(function (req, res) {
  response = {
    error: false,
    code: 200,
    message: "Expediente Carlos",
    data: cr,
  };

  res.send(response);
});

app.use(function (req, res) {
  response = {
    error: true,
    codigo: 404,
    mensaje: "URL not found",
  };
  res.status(404).send(response);
});
app.listen(port, () => {
  console.log("Server started. Port 3000");
  console.log("Login user created");
  console.log("email: " + loginUser.email);
  console.log("password: " + loginUser.password);
});
